@id=00000000-0000-0000-0000-000000000000

PUT http://localhost:5023/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "Description": "Vegan everything",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "Savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Sallad"
    ],
    "Sweet": [
        "Cookie"
    ]
}